web:
  build: .
  links:
    - mysql
  ports:
    - "8080:80"
  command: /scripts/dev.env.sh /run.sh

mysql:
  image: mysql:5.6
  environment:
     - MYSQL_DATABASE=smt2
     - MYSQL_USER=test
     - MYSQL_PASSWORD=test
     - MYSQL_ROOT_PASSWORD=verysecret
